title: PWWPCHE
description: No description here

url: https://github.com/pwwpche
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: pwwpche
   email: pwwpche@gmail.com

google_analytics: ""
